name: Blog CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: git config --global user.email "tsangkalung@bupt.edu.cn"
      - run: git config --global user.name "TsangKalung"
      - shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm run deploy
